services:
  db:
    image: postgres:latest
    container_name: pms_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    command: >
      postgres -c listen_addresses=*
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  patient-service:
    build: ./patient-service
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - patient-service
    restart: on-failure

volumes:
  pgdata:
