server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/api/patient/**
          filters:
            - StripPrefix=2

eureka:
  client:
    enabled: false
