server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8081
          predicates:
            - Path=/api/patients/**
        - id: vitals-service
          uri: http://vitals-service:8082
          predicates:
            - Path=/api/vitals/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
